### PR TITLE
optimize bootstrap algorithm

### PR DESCRIPTION
**Pull request by greeshka**
There is no need to sort the `deltas` array. Zero will be inserted on the ith position, where i is number of elements less than 0. Therefore one can simply count number of elements less than zero and put that number in `positions`.

This code is more efficient and short.

### CODE REVIEW

**Comment by marnikitta** [comment]
Hi, @greeshka. That makes sense. As a little improvement, `np.sum(..., axis=1)` is a more numpy way and probably a little bit more efficient.

**Comment by greeshka** [comment]
Hi. Agreed, this one would be even better.

**Comment by greeshka** [comment]
Hi!
I remembered about this one just now :)

**Comment by marnikitta** [comment]
Thanks!

**Pull request merged**
