### PR TITLE
buckets_ctrs typo fixed

### PR DESCRIPTION
**Pull request by nefomichev**

### CODE REVIEW

**Comment by marnikitta** [comment]
Thanks!

**Comment by nefomichev** [comment]
@marnikitta  

Никита, привет ! Спасибо за интересную статью и код. 

Заодно хотел задать вопрос по реализации бакетного метода: 
https://github.com/marnikitta/stattests/blob/97cdb36d6ca0fa96da06b65eaa4ea69fbaddd427/stattests/tests.py#L85-L89

Почему здесь числитель раскладывается на ctrs & weights(aka. views), а не используются clicks? Например вот так: 
```
 for b in np.arange(n_buckets):
        ind = np.arange(b * n_users / n_buckets, b * n_users / n_buckets + n_users / n_buckets).astype(np.int)
        values_0[:, b] = np.sum(clicks_0[:, ind], axis=1) / np.sum(weights_0[:, ind], axis=1)
        values_1[:, b] = np.sum(clicks_1[:, ind], axis=1) / np.sum(weights_1[:, ind], axis=1)
```

**Comment by marnikitta** [comment]
You assume that `views == weights`. It is the case for global CTR, but it doesn't hold for "effective sample size" weighting ([Section 4.4. of the article](https://vkteam.medium.com/practitioners-guide-to-statistical-tests-ed2d580ef04f#ca28)).

**Comment by marnikitta** [comment]
This code also works with other kinds of metrics and arbitrary weights. For example, you can take clicks as metric and some normalised LTV as weights. This way, metric will prioritise more profitable users

**Comment by nefomichev** [comment]
Thank you for the explanation ! 

It looks clear for me now.

**Pull request merged**
